### ISSUE TITLE
no rtst support

### ISSUE THREAD

**Issue by jayson8121** [dadycoding/IjkplayerXamarin#3]
rtsp://113.136.42.45:554/PLTV/88888888/224/3221226087/10000100000000060000000001759104_0.smil

display "unknow error"

**Comment by jaceDeng** [comment]
rtsp need to recompile  ijkplayer ,then replace  the so  file
https://www.jianshu.com/p/ded73b154356

**Comment by jaceDeng** [comment]
add rtsp support
