### ISSUE TITLE
编译时不通过，乱码提示

### ISSUE THREAD

**Issue by piayping** [dadycoding/IjkplayerXamarin#4]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误		閿欒: OnDownloadStateListener鍦‥NDownloadView涓笉鏄叕鍏辩殑; 鏃犳硶浠庡閮ㄧ▼搴忓寘涓鍏惰繘琛岃闂?
		moe.codeest.enviews.ENDownloadView.OnDownloadStateListener
娉? 鏌愪簺杈撳叆鏂囦欢浣跨敤鎴栬鐩栦簡宸茶繃鏃剁殑 API銆?
娉? 鏈夊叧璇︾粏淇℃伅, 璇蜂娇鐢?-Xlint:deprecation 閲嶆柊缂栬瘧銆?
娉? 鏌愪簺杈撳叆鏂囦欢浣跨敤浜嗘湭缁忔鏌ユ垨涓嶅畨鍏ㄧ殑鎿嶄綔銆?
娉? 鏈夊叧璇︾粏淇℃伅, 璇蜂娇鐢?-Xlint:unchecked 閲嶆柊缂栬瘧銆?
1 涓敊璇?	IjkplayerXamarin.Android	C:\Users\xcj\Desktop\IjkplayerXamarin-master\IjkplayerXamarin\IjkplayerXamarin\IjkplayerXamarin.Android\obj\Release\81\android\src\mono\moe\codeest\enviews\ENDownloadView_OnDownloadStateListenerImplementor.java	8

**Comment by jaceDeng** [comment]
已经处理了  请拉最新的
